### ISSUE TITLE
ImportError: cannot import name 'mplayerQueue' from 'anki.sound' (C:\Program Files\Anki\anki\sound.pyc)

### ISSUE THREAD

**Issue by xx299x** [yu7777/Control-Audio-Playback-Speed#3]
As upgrading Anki, this add-on doesn't work. I found out some useful information for you.
```
Traceback (most recent call last):
File "aqt\addons.py", line 205, in loadAddons
File "C:\Users\ancat\AppData\Roaming\Anki2\addons21\1067025219\__init__.py", line 1, in <module>
from . import Audio_Controls
File "C:\Users\ancat\AppData\Roaming\Anki2\addons21\1067025219\Audio_Controls.py", line 10, in <module>
from anki.sound import mplayerQueue, mplayerClear, mplayerEvt
ImportError: cannot import name 'mplayerQueue' from 'anki.sound' (C:\Program Files\Anki\anki\sound.pyc)
```
I browse the log of upgrading Anki. following informaiton is useful perhaps.
https://changes.ankiweb.net/#/?id=changes-in-2117

**Comment by mohammadkazemi** [comment]
![image](https://user-images.githubusercontent.com/25531130/91869589-52ae8600-ec8b-11ea-9f0e-4ffa9e6ef608.png)
